import Head from 'next/head';
import Image from "next/image";
import languages from "../public/languages.png";
import technologies from "../public/technologies.png";
import methods from "../public/methods.png";
import { useState } from "react";
import portrait1 from "../public/portrait1.jpg";
import github2 from "../public/github2.png";
import linkedin2 from "../public/linkedin2.png";
import moon from "../public/moon.png";
import sun from "../public/sun.png";
import htmlicon from "../public/htmlicon.png";
import cssicon from "../public/cssicon.png";
import pythonicon from "../public/pythonicon.png";
import javascripticon from "../public/javascripticon.png";
import sqlicon from "../public/sqlicon.png";
import flaskicon from "../public/flaskicon.png";
import vscodeicon from "../public/vscodeicon.png";
import pycharmicon from "../public/pycharmicon.png";
import postgresicon from "../public/postgresicon.png";
import cicdicon from "../public/cicdicon.png";
import devopsicon from "../public/devopsicon.png";
import sdlcicon from "../public/sdlcicon.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Thomas Balicki Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-stone-100 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Portfolio</h1>
            <ul className='flex items-center'>
              <li>
                <Image
                  src={darkMode ? moon : sun}
                  width={40}
                  height={40}
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer hover:scale-105 transition-transform"
                />
              </li>
              <li>
                <a href="https://github.com/thomasbalicki">
                  <Image src={github2} width={35} height={35} className="cursor-pointer mx-5" />
                </a>
              </li>
              <li>
                <a href="https://www.linkedin.com/in/thomas-balicki-3105ba205/">
                  <Image src={linkedin2} width={35} height={35} className="cursor-pointer" />
                </a>
              </li>
              <li>
                <a className="bg-gradient-to-r from-red-400 to-orange-400 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-8 dark:text-white'>
            <h2 className='text-5xl py-2 text-red-500 font-medium md:text-6xl'>Thomas Balicki</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Software Developer.</h3>
            <p className='text-md py-4 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Hi there, I'm Tom - a programmer and web developer from Milwaukee. Despite only beginning my programming journey a year ago, it's become my biggest passion, pushing me to continually learn and improve my skills. Seeing something I've created from scratch come to life online is a truly incredible feeling. I'm excited to keep exploring this ever-evolving field and see where my passion takes me next. Thank you for taking the time to learn a little bit about me, and I can't wait to share more with you!</p>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-red-400 rounded-full w-80 h-80 mt-15 overflow-hidden md:h-96 md:w-96 dark:outline outline-2 outline-red-500">
            <Image src={portrait1} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-5 text-red-400'>Skills</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              With a solid foundation in several programming languages and frameworks, including HTML, CSS with Tailwind, Python, JavaScript (with a focus on React), SQL, and Flask, I am confident in my abilities to tackle a wide range of programming challenges. I am proficient in using various tools such as VS Code and PyCharm for coding, as well as Github for version control. Additionally, I have experience working with PostgresSQL and PGAdmin for managing databases. I have a basic understanding of the software development life cycle (SDLC) methodologies and am familiar with continuous integration/continuous deployment (CI/CD) workflows. I am also knowledgeable in DevOps practices and am committed to implementing them in my work. I am eager to continue learning and expanding my skillset in order to take on even more complex projects in the future.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="bg-gradient-to-tr from-red-100 to-orange-100 flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-red-400">
              <div className="flex items-center justify-center">
                <Image src={languages} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">My Stack</h3>
              </div>
              <h4 className="py-4 text-lg text-red-600">Languages & Frameworks</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={htmlicon} width={30} height={30} />
                <p className="text-gray-800 py-1">HTML</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={cssicon} width={30} height={30} />
                <p className="text-gray-800 py-1">CSS, Tailwind</p>
              </div>
              <div className="flex flex-row items-center justify-start">
                <Image src={pythonicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Python</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={javascripticon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">JavaScript, React</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={sqlicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">SQL</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={flaskicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Flask</p>
              </div>
            </div>
            <div className="bg-gradient-to-tr from-orange-100 to-red-100 flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-red-400 dark:bg-stone-100">
              <div className="flex items-center justify-center">
                <Image src={technologies} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">Technologies</h3>
              </div>
              <h4 className="py-4 text-lg text-red-600">Tools I use</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={vscodeicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">VS Code</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={pycharmicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">PyCharm</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={postgresicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">PostgresSQL/PGAdmin</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={github2} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Github</p>
              </div>
              <p className="text-gray-800 py-1 px-1 flex flex-row">And many more..</p>
            </div>
            <div className="bg-gradient-to-tr from-orange-100 to-red-100 flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-red-400 dark:bg-stone-100">
              <div className="flex items-center justify-center">
                <Image src={methods} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">Methods</h3>
              </div>
              <h4 className="py-4 text-lg text-red-600">My workflow</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={sdlcicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">SDLC</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={cicdicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">CI/CD</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={devopsicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">DevOps</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 text-red-400'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
            </p>
            <p>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
                Ut enim ad minim veniam, <span className="text-red-400 dark:text-red-400">quis nostrud</span> exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.
              </p>
            </p>
          </div>
          <footer class="bg-stone-100 text-black py-10">
            <div class="container mx-auto text-center">
              <p>&copy; 2023 My Website. All rights reserved.</p>
            </div>
          </footer>
        </section>
      </main>
    </div>
  )
}
