import Head from 'next/head';
import Image from "next/image";
import languages from "../public/languages.png";
import technologies from "../public/technologies.png";
import methods from "../public/methods.png";
import { useState } from "react";
import portrait1 from "../public/portrait1.jpg";
import github2 from "../public/github2.png";
import linkedin2 from "../public/linkedin2.png";
import moon from "../public/moon.png";
import sun from "../public/sun.png";
import htmlicon from "../public/htmlicon.png";
import cssicon from "../public/cssicon.png";
import pythonicon from "../public/pythonicon.png";
import javascripticon from "../public/javascripticon.png";
import sqlicon from "../public/sqlicon.png";
import flaskicon from "../public/flaskicon.png";
import vscodeicon from "../public/vscodeicon.png";
import pycharmicon from "../public/pycharmicon.png";
import postgresicon from "../public/postgresicon.png";
import cicdicon from "../public/cicdicon.png";
import devopsicon from "../public/devopsicon.png";
import sdlcicon from "../public/sdlcicon.png";
import collegeicon from "../public/collegeicon.png"
import mastodonicon from "../public/mastodonicon.png";
import scroll from "../public/scroll.png";
import construction from "../public/construction.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showSkills, setShowSkills] = useState(true);

  const handleSkillsClick = () => {
    setShowSkills(true);
  };
  const handleEducationClick = () => {
    setShowSkills(false);
  };


  return (

    <div className={darkMode ? "dark" : ""}>

      {/*-------------------------------------------Page Header------------------------------------------------------------------*/}
      <Head>
        <title>Thomas Balicki Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolioicon.png" />
      </Head>
      <main className='bg-stone-100 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>

          {/*-------------------------------------------My Nav Bar------------------------------------------------------------------*/}

          <nav className='py-10 mb-10 flex sm:flex-row justify-between'>
            <h1 className='text-xl font-burtons dark:text-white pb-1'>Portfolio</h1>
            <ul className='flex items-center'>
              <li>
                <Image
                  src={darkMode ? moon : sun}
                  width={40}
                  height={40}
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer hover:scale-105 transition-transform mx-1"
                />
              </li>
              <li>
                <a href="https://github.com/thomasbalicki">
                  <Image src={github2} width={30} height={30} className="cursor-pointer hover:scale-105 transition-transform mx-1" />
                </a>
              </li>
              <li>
                <a href="https://www.linkedin.com/in/thomas-balicki-3105ba205/">
                  <Image src={linkedin2} width={30} height={30} className="cursor-pointer hover:scale-105 transition-transform mx-1" />
                </a>
              </li>
              <li>
                <a href="https://vmst.io/@ThomasTheTrainwreck">
                  <Image src={mastodonicon} width={30} height={30} className="cursor-pointer hover:scale-105 transition-transform mx-1" />
                </a>
              </li>
              <li>
                <a className="bg-gradient-to-r from-teal-400 to-blue-400 text-white px-3 py-2 rounded-md mx-1" href="#">Resume</a>
              </li>
            </ul>
          </nav>

          {/*-------------------------------------------NAME AND INTRO------------------------------------------------------------------*/}
          <div className='flex flex-wrap items-center justify-center pb-10'>
            <div className='p-5 dark:text-white w-full md:w-1/2'>
              <h2 className='text-4xl py-2 text-teal-500 font-medium md:text-6xl dark:text-teal-400'>Thomas Balicki</h2>
              <h3 className='text-2xl py-2 md:text-3xl'>Software Developer.</h3>
              <p className='text-md py-2 leading-8 text-gray-800 md:text-xl max-w-xl dark:text-white'>Hi there, I'm Tom - a programmer and web developer from Milwaukee. Despite only beginning my programming journey a year ago, it's become my biggest passion, pushing me to continually learn and improve my skills. Seeing something I've created from scratch come to life online is a truly incredible feeling. I'm excited to keep exploring this ever-evolving field and see where my passion takes me next. Thank you for taking the time to learn a little bit about me, and I can't wait to share more with you!</p>
            </div>
            <div className="relative rounded-full w-80 h-80 mt-10 md:mt-0 overflow-hidden md:h-96 md:w-96 dark:outline outline-2 outline-teal-500" style={{ marginBottom: '-40px' }}>
              <Image src={portrait1} layout="fill" objectFit="cover" className="rounded-full" />
            </div>
          </div>
        </section>
        <section>

          {/*-------------------------------------------Skills section & paragraph------------------------------------------------------------------*/}

          <div className='shadow-xl p-5 rounded-xl my-10 outline outline-2 outline-teal-400 dark:bg-gray-500 dark:bg-opacity-10'>
            <button className='hover:bg-teal-300 transition-transform bg-teal-400 text-white text-1xl px-3 py-1 rounded-md mx-2' onClick={handleSkillsClick}>Skills</button>
            <button className='hover:bg-teal-300 transition-transform bg-teal-400 text-white text-1xl px-3 py-1 rounded-md mx-2' onClick={handleEducationClick}>Education</button>
            {showSkills ? (
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
                With a solid foundation in several programming languages and frameworks, including <span className="text-teal-400">HTML, CSS with Tailwind, Python, JavaScript (with a focus on React), SQL, and Flask</span>, I am confident in my abilities to tackle a wide range of programming challenges. I am proficient in using various tools such as <span className="text-teal-400">VS Code and PyCharm</span> for coding, as well as <span className="text-teal-400">Github</span> for version control. Additionally, I have experience working with <span className="text-teal-400">PostgresSQL and PGAdmin</span> for managing databases. I have a basic understanding of the software development life cycle (SDLC) methodologies and am familiar with continuous integration/continuous delivery (CI/CD) workflows. I am also knowledgeable in DevOps practices and am committed to implementing them in my work. I am eager to continue learning and expanding my skillset in order to take on even more complex projects in the future.
              </p>
            ) : (
              <div className="flex-1 p-5 text-lg items-center justify-start py-5 mx-2">
                <div className="flex flex-row items-center justify-start">
                  <Image src={collegeicon} width={30} height={30} />
                  <p className='mx-2 dark:text-white'><span className="text-teal-500">University of Wisconsin Milwaukee</span> - Bachelors Business Marketing</p>
                </div>
                <div className="flex flex-row items-center justify-start py-5">
                  <Image src={scroll} width={30} height={30} />
                  <p className='mx-2 dark:text-white'><span className="text-teal-500">Nucamp Coding Bootcamp</span> - Back End, SQL, and DevOps Developer with Python</p>
                </div>
                <div className="flex flex-row items-center justify-start">
                  <Image src={scroll} width={30} height={30} />
                  <p className='mx-2 dark:text-white'><span className="text-teal-500">Nucamp Coding Bootcamp</span> - Full Stack Web and Mobile App Developer</p>
                </div>
              </div>
            )}
          </div>
          <div className="lg:flex gap-10">

            {/*-------------------------------------------My Stack Div------------------------------------------------------------------*/}

            <div className="bg-white flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-teal-400">
              <div className="flex items-center justify-center">
                <Image src={languages} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">My Stack</h3>
              </div>
              <h4 className="py-4 text-lg text-teal-500">Languages & Frameworks</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={htmlicon} width={30} height={30} />
                <p className="text-gray-800 py-1">HTML</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={cssicon} width={30} height={30} />
                <p className="text-gray-800 py-1">CSS, Tailwind</p>
              </div>
              <div className="flex flex-row items-center justify-start">
                <Image src={pythonicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Python</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={javascripticon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">JavaScript, React</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={sqlicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">SQL</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={flaskicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Flask</p>
              </div>
            </div>

            {/*-------------------------------------------My Technologies Div------------------------------------------------------------------*/}

            <div className="bg-white flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-teal-400">
              <div className="flex items-center justify-center">
                <Image src={technologies} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">Technologies</h3>
              </div>
              <h4 className="py-4 text-lg text-teal-500">Tools I use</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={vscodeicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">VS Code</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={pycharmicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">PyCharm</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={postgresicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">PostgresSQL/PGAdmin</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={github2} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">Github</p>
              </div>
              <p className="text-gray-800 py-1 px-1 flex flex-row">And many more..</p>
            </div>

            {/*-------------------------------------------My Methods Div------------------------------------------------------------------*/}

            <div className="bg-white flex-1 text-center shadow-xl p-10 rounded-xl my-10 outline outline-2 outline-teal-400">
              <div className="flex items-center justify-center">
                <Image src={methods} width={50} height={50} />
                <h3 className="text-2xl font-medium ml-4">Methods</h3>
              </div>
              <h4 className="py-4 text-lg text-teal-500">My workflow</h4>
              <div className="flex flex-row items-center justify-start">
                <Image src={sdlcicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">SDLC</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={cicdicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">CI/CD</p>
              </div>
              <div className="flex flex-row items-center justify-start py-1">
                <Image src={devopsicon} width={30} height={30} />
                <p className="text-gray-800 py-1 px-1">DevOps</p>
              </div>
            </div>
          </div>
        </section>

        {/*-------------------------------------------My Portfolio Section------------------------------------------------------------------*/}

        <section>
          <div>
            <h3 className='text-3xl py-1 text-teal-400'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Hello! The portfolio section of my website is currently under development, but I'm putting in the effort to add my projects soon. You can view what I'm currently working on by clicking on the Github icon located at the top of the page which will direct you to my Github profile. There, you can explore all of my projects, browse through the code, and read the documentation for each one. Thank you for visiting my website, and I hope you enjoy my projects!
            </p>
          </div>
        </section>

        {/*-------------------------------------------Contact Me Section------------------------------------------------------------------*/}

        <section>
          <div className='flex justify-end'>
            <h3 className='text-3xl pt-10 text-teal-400'>Contact Me</h3>
          </div>
          <div className='flex justify-end'>
            <form action="/contact" method="POST" class="max-w-md bg-stone-100 flex-1 shadow-xl p-5 rounded-xl my-10 outline outline-2 outline-teal-400 dark:bg-gray-500 dark:bg-opacity-10">
              <div class="mb-4">
                <label class="block text-teal-400 text-sm font-bold mb-2" for="name">
                  Name
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="name" type="text" placeholder="Your name" />
              </div>
              <div class="mb-4">
                <label class="block text-teal-400 text-sm font-bold mb-2" for="email">
                  Email
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Your email" />
              </div>
              <div class="mb-4">
                <label class="block text-teal-400 text-sm font-bold mb-2" for="message">
                  Message
                </label>
                <textarea class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="message" placeholder="Your message"></textarea>
              </div>
              <div class="flex items-center justify-between">
                <button class="bg-teal-400 hover:bg-teal-300 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                  Send
                </button>
              </div>
            </form>
          </div>
        </section>


        {/*-------------------------------------------Footer Section------------------------------------------------------------------*/}

        <footer className="bg-stone-100 text-black py-10 dark:text-white dark:bg-gray-900">
          <div className="container mx-auto text-center">
            <p>&copy; 2023 My Website. All rights reserved.</p>
          </div>
        </footer>

      </main>
    </div>
  )
}
